language: ruby
deploy:
  provider: heroku
  api_key:
    secure: FAZOuIAaR7vYzZr3lUfR5mhb2tGD5RQmzBr/lYkqUfW+ubw0yeF964/tozklC6yBakbK52rqaASQq3e8SQ2PmYCfbiUb4/1dDovT4MXGkOrnis9Mer0G+rxtlnhdaTBFTVySQLmnnVuDMatmTgdQ/OttkoaPskKJy/WZvYdQY9nktu0gOjdxnov41rT/1ysFsCjOLXKCTY334JLeKKdkBIx2kGgczgiNDg6nkHLdNWRJtOZrWc5Wos+cjqibpqvjqKQVQe2jsxT7DGa44KDB4Oif97DXLH/6iDlztVVLXn5w3T71568e3clhRl9eKqY5cxVtnHiWVG7AvYjIJniT8xM9C0q5Px3fQJ6IIBclIVHFtvAKDpoZE0nYd6GGE/y8TWGX7p+duXiilYeqPwl6Yw+RAM/y88qR7RvLMfAv3dFq2t9GaewNti5exkq3NbSbuY9/2PgFEkNgRiiv+R3kILEHR7SPRZhF+HFdgGk2dycLHE8C2Qhfqg1jBkAd46z499KfgwR6VSMWdJIHQ38DbW3GVazeKUdJ5cSaVGxJ07Lfk0untFZmI+LhgCmc5KxOd1l+K2beDBgOrzVfG5d1IbJIZ2h3f74sJLhYFczHbsK36wshkc0QxtqZoaA8dUvPyyyo7qMi7nCnLYFOmnC5FKgODEKCGAGAO/diiauk1/w=
  run: "rake db:migrate"
